### ISSUE TITLE
x 5

### ISSUE THREAD

**Issue by Davo911** [donadev/TicTacToe#47]
### Instructions

Please replace in the title the char "$" with the index of your move, following the schema:

| x | o | 3  |
| :-: | :-: | :-: |
| 4 | x | 6 |
| 7 | 8 | 9 |

### Rules
- if you break the game rules, the move will not be applied.
- If the move is authorized, it will display with your name on the readme in approx 20 seconds.

**Comment by donadev** [comment]
@Davo911 you need to resubmit with the correct title that's "x 5"
